// Tops/Bottoms/ Dresses/Jackets/Shoes/Accesories/Sale
const products = [
  {
    name: "SPRING SUMMER 2015",
    code: "AX142",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 70,
    imageCover:
      "https://tse4.mm.bing.net/th?id=OIP.CKJ9HLX9-Hkf6Q1NyJSFTgHaLG&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 10,
    size: ["S", "M", "L"],
    color: ["red", "light-gold", "white", "black"],
    brand: ["Zara", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Casual dresses",
  },
  {
    name: "BURBERRY PRORSUM",
    code: "AX143",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 10,
    imageCover:
      "https://tse3.mm.bing.net/th?id=OIP.cTMBqRUg12j7oZgKTinzOgHaLH&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 10,
    size: ["S", "M", "L", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Going out dresses",
  },
  {
    name: "Runway-Costume",
    code: "AX144",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 20,
    imageCover:
      "https://www.theskinnybeep.com/wp-content/uploads/2014/09/Runway-Costume-National-Summer-2015-Women-Collection-Milan-Fashion-Week.jpg",
    images: [],
    quantity: 0,
    size: ["S", "L", "XLL"],
    color: ["orange", "charcoal-grey", "white", "black"],
    brand: ["Zara", "H&M", "Pull&Bear"],
    person: "Ladies",
    type: "Dresses",
    category: "Rompers / Jumpsuits",
  },
  {
    name: "Marchesa-Spring-Summer",
    code: "AX145",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 20,
    imageCover:
      "https://www.fashionotography.com/wp-content/uploads/2020/09/Marchesa-Spring-Summer-2021-New-York-Fashion-Week-18.jpeg",
    images: [],
    quantity: 10,
    size: ["S", "M", "L", "XLL"],
    color: ["red", "light-gold", "cornflower"],
    brand: ["Zara", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Party / Ocassion dresses",
  },
  {
    name: "ETRO WOMEN",
    code: "AX146",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 20,
    imageCover:
      "https://socialproofimage.com/wp-content/uploads/2020/09/ETRO-WOMENS-SPRINGSUMMER-2021-6.jpg",
    images: [],
    quantity: 10,
    size: ["S", "M", "L", "XLL"],
    color: ["red", "light-gold", "charcoal-grey", "white", "black"],
    brand: ["H&M", "Pull&Bear", "Dior"],
    person: "Ladies",
    type: "Dresses",
    category: "Mini dresses",
  },
  {
    name: "Runway Spring 2016",
    code: "AX147",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 100,
    imageCover:
      "https://tse4.mm.bing.net/th?id=OIP.n9iqJwr0jyW9Yyu_uSsD-gHaLH&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 10,
    size: ["S", "M", "L", "XLL"],
    color: ["red", "light-gold", "cornflower", "orange"],
    brand: ["Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Party / Ocassion dresses",
  },
  {
    name: "moschino-autumn-winter",
    code: "AX148",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 60,
    imageCover:
      "https://data.ibtimes.sg/en/full/21136/moschino-autumn-winter-2018-women-collection-during-milan-fashion-week-in-milan.jpg?w=1180",
    images: [],
    quantity: 50,
    size: ["S", "M"],
    color: ["cornflower", "orange", "white", "black"],
    brand: ["Zara", "H&M", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Casual dresses",
  },
  {
    name: "Off-white women",
    code: "AX149",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 30,
    imageCover:
      "https://tse1.mm.bing.net/th?id=OIP.yYotkzKPQLkKFWywYLOYcgHaLI&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 0,
    size: ["S", "M", "L", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Zara", "H&M", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Going out dresses",
  },
  {
    name: "Love of pink",
    code: "AX150",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 200,
    imageCover:
      "https://tse4.mm.bing.net/th?id=OIP.6p3DZeQ8dlJd1W6TZI5HQAHaL9&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 150,
    size: ["S", "M", "L", "XLL"],
    color: ["red", "light-gold", "charcoal-grey", "white", "black"],
    brand: ["Zara", "H&M", "Pull&Bear"],
    person: "Ladies",
    type: "Dresses",
    category: "Mini dresses",
  },
  {
    name: "Women-channel-trend",
    code: "AX151",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 250,
    imageCover:
      "http://www.theskinnybeep.com/wp-content/uploads/2018/03/2018-Woman-Chanel-Trends-Paris-Fashion-Week.jpg",
    images: [],
    quantity: 500,
    size: ["S", "M", "L", "XLL"],
    color: ["cornflower", "orange", "charcoal-grey", "white", "black"],
    brand: ["Zara", "H&M", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Rompers / Jumpsuits",
  },
  {
    name: "Spring-summer",
    code: "AX152",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 120,
    imageCover:
      "https://tse2.mm.bing.net/th?id=OIP.kNLAxUndOlPff7qlsa3IYgHaK7&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 80,
    size: ["S", "XLL"],
    color: ["cornflower", "orange", "charcoal-grey", "white", "black"],
    brand: ["Zara", "H&M", "Pull&Bear"],
    person: "Ladies",
    type: "Dresses",
    category: "Mini dresses",
  },
  {
    name: "Calvin-Klein-Fall-Winter",
    code: "AX-153",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 260,
    imageCover:
      "http://www.theskinnybeep.com/wp-content/uploads/2015/02/Catwalk-Calvin-Klein-Fall-Winter-2015-16-Women-Collection-New-York-Fashion-Week.jpg",
    images: [],
    quantity: 60,
    size: ["M", "L", "XLL"],
    color: ["red", "light-gold", "charcoal-grey", "white", "black"],
    brand: ["Zara", "H&M", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Party / Ocassion dresses",
  },
  {
    name: "Mix Spring-Winter",
    code: "AX-154",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 160,
    imageCover:
      "https://tse1.mm.bing.net/th?id=OIP.ejZUBJH1zWZTrpNkruDE1wHaLH&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 0,
    size: ["S", "M", "L"],
    color: ["red", "light-gold", "cornflower", "orange", "black"],
    brand: ["Zara", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Rompers / Jumpsuits",
  },
  {
    name: "Peter Spring",
    code: "AX-155",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 240,
    imageCover:
      "https://tse3.mm.bing.net/th?id=OIP.lxrf0HTcjb9A3-wQJ9EvPgHaLG&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 200,
    size: ["S", "L", "XLL"],
    color: ["cornflower", "orange", "charcoal-grey", "white", "black"],
    brand: ["Zara", "H&M", "Pull&Bear", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Mini dresses",
  },
  {
    name: "Thornton-Bregazzi-Fall-Winter",
    code: "AX-156",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 170,
    imageCover:
      "https://www.theskinnybeep.com/wp-content/uploads/2015/03/Runway-Preen-by-Thornton-Bregazzi-Fall-Winter-2015-16-Women-Collection-London-Fashion-Week.jpg",
    images: [],
    quantity: 9,
    size: ["S", "M", "L"],
    color: ["light-gold", "cornflower", "orange", "charcoal-grey"],
    brand: ["Zara", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Going out dresses",
  },
  {
    name: "",
    code: "AX-157",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 20,
    imageCover: "",
    images: [],
    quantity: 10,
    size: ["S", "M", "L", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Zara", "H&M", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "",
  },
  {
    name: "Versace Spring Summer",
    code: "AX-158",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 260,
    imageCover:
      "https://tse4.mm.bing.net/th?id=OIP.WgOOH0qBzVqvqho15OE5-wHaLI&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 10,
    size: ["S", "L", "XLL"],
    color: ["red", "light-gold", "cornflower", "orange", "black"],
    brand: ["Zara", "H&M", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Rompers / Jumpsuits",
  },
  {
    name: "ETRO Fall Winter",
    code: "AX-159",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 190,
    imageCover:
      "http://www.theskinnybeep.com/wp-content/uploads/2017/04/Fashion-Woman-Model-Etro-Catwalk-17-18.jpg",
    images: [],
    quantity: 10,
    size: ["S", "M", "XLL"],
    color: ["red", "orange", "charcoal-grey", "white", "black"],
    brand: ["Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Party / Ocassion dresses",
  },
  {
    name: "N21 Spring Winter",
    code: "AX-160",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 85,
    imageCover:
      "https://tse3.explicit.bing.net/th?id=OIP.BDTqoP2aE-KOzp2wvEBxfwHaLI&pid=Api&P=0&w=300&h=300",
    images: [],
    quantity: 90,
    size: ["S", "M", "L", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Zara", "H&M", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Casual dresses",
  },
  {
    name: "Dsquared2-Spring-Summer",
    code: "AX-170",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 245,
    imageCover:
      "https://www.theskinnybeep.com/wp-content/uploads/2011/10/Dsquared2-Spring-Summer-2012-Women-Fashion-Show.jpg",
    images: [],
    quantity: 0,
    size: ["S", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Zara", "H&M", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "Mini dresses",
  },
  {
    name: "Spring party dress",
    code: "AX-171",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 80,
    imageCover:
      "https://d.ibtimes.co.uk/en/full/1363308/london-fashion-week.jpg",
    images: [],
    quantity: 250,
    size: ["S", "M", "L", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Zara", "H&M", "Dior"],
    person: "Ladies",
    type: "Dresses",
    category: "Going out dresses",
  },
  {
    name: "",
    code: "AX-172",
    description: ["Chest: 36”", "Length: 25.75”"],
    price: 20,
    imageCover: "",
    images: [],
    quantity: 10,
    size: ["S", "M", "L", "XLL"],
    color: [
      "red",
      "light-gold",
      "cornflower",
      "orange",
      "charcoal-grey",
      "white",
      "black",
    ],
    brand: ["Zara", "H&M", "Pull&Bear", "Dior", "Chanel"],
    person: "Ladies",
    type: "Dresses",
    category: "",
  },
];
